# Generated by Django 5.2.2 on 2025-06-07 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("description", models.TextField()),
                (
                    "service_type",
                    models.CharField(
                        choices=[
                            ("cleaning", "Cleaning"),
                            ("plumbing", "Plumbing"),
                            ("electrical", "Electrical"),
                            ("gardening", "Gardening"),
                        ],
                        max_length=50,
                    ),
                ),
                ("location", models.CharField(max_length=100)),
                ("available", models.BooleanField(default=True)),
            ],
        ),
    ]
